jobs:
    - job: stciker_server_build # name of the deployment job, A-Z, a-z, 0-9, and underscore
      displayName: Build Sticker Server API # friendly name to display in the UI
      pool:
          vmImage: "ubuntu-18.04"
      steps:
          - task: UseNode@1
            displayName: "Use Node version"

          - task: Npm@1
            displayName: "npm install"
            inputs:
                workingDir: server
                verbose: false

          - task: Npm@1
            displayName: "npm run build"
            inputs:
                command: custom
                workingDir: server
                verbose: true
                customCommand: "run build"

          - task: Npm@1
            displayName: "npm ci --only=production"
            inputs:
                command: custom
                workingDir: server
                verbose: true
                customCommand: "ci --only=production"

          - task: ArchiveFiles@2
            displayName: "Archive server"
            inputs:
                rootFolderOrFile: server
                includeRootFolder: false

          - task: CopyFiles@2
            displayName: "Copy File to: $(TargetFolder)"
            inputs:
                SourceFolder: "$(Build.ArtifactStagingDirectory)"
                Contents: "$(Build.BuildId).zip"
                TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: drop"
            inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
